
spring.datasource.url=jdbc:postgresql://localhost:5555/Satapp-V1
spring.datasource.username=admin
spring.datasource.password=admin
spring.sql.init.mode=always
spring.jpa.properties.hibernate.hbm2ddl.import_files_sql_extractor=org.hibernate.tool.schema.internal.script.MultiLineSqlScriptExtractor